### ISSUE TITLE
Case incompatibility

### ISSUE THREAD

**Issue by fow0ryl** [holgerlembke/serialtcp#1]
Hallo Holger,
working on my first ESP32 project I downloaded actual version (as a zip file) with ESP32 support. After adding it to the Arduino IDE (on linux, what else?) it didn't work. Since native C is case sensitive, and so is linux, the files serialtcp.h and serialtcp.cpp cannot be found.
My solution was to rename them to serialTCP.h and serialTCP.cpp.
It would be nice if you can change the filenames for best compatibility ...
LG
Henning

**Comment by holgerlembke** [comment]
Moin fow0ryl,

thanks for bringing this to my attention. As a windows user, I tend to make this error.... 

I reuploaded the files with fixed file names.
